export enum ActionTypes {
    // User actions
    USER_DATA = "USER_DATA",
    CLEAR_USER = "CLEAR_USER",
    
    // Scanner results
    SET_APK_RESULTS = "SET_APK_RESULTS",
    SET_WHATSAPP_RESULTS = "SET_WHATSAPP_RESULTS",
    SET_JUNK_FILE_RESULTS = "SET_JUNK_FILE_RESULTS",
    SET_LARGE_FILE_RESULTS = "SET_LARGE_FILE_RESULTS",
    SET_OLD_FILE_RESULTS = "SET_OLD_FILE_RESULTS",
    SET_CACHE_LOGS_RESULTS = "SET_CACHE_LOGS_RESULTS",
    SET_DUPLICATE_RESULTS = "SET_DUPLICATE_RESULTS",
    SET_UNUSED_APPS_RESULTS = "SET_UNUSED_APPS_RESULTS",
    
    // Clear results
    CLEAR_APK_RESULTS = "CLEAR_APK_RESULTS",
    CLEAR_WHATSAPP_RESULTS = "CLEAR_WHATSAPP_RESULTS",
    CLEAR_JUNK_FILE_RESULTS = "CLEAR_JUNK_FILE_RESULTS",
    CLEAR_LARGE_FILE_RESULTS = "CLEAR_LARGE_FILE_RESULTS",
    CLEAR_OLD_FILE_RESULTS = "CLEAR_OLD_FILE_RESULTS",
    CLEAR_CACHE_LOGS_RESULTS = "CLEAR_CACHE_LOGS_RESULTS",
    CLEAR_DUPLICATE_RESULTS = "CLEAR_DUPLICATE_RESULTS",
    CLEAR_UNUSED_APPS_RESULTS = "CLEAR_UNUSED_APPS_RESULTS",
    
    // Selected items
    SET_SELECTED_ITEMS = "SET_SELECTED_ITEMS",
    TOGGLE_ITEM_SELECTION = "TOGGLE_ITEM_SELECTION",
    CLEAR_SELECTIONS = "CLEAR_SELECTIONS",
    
    // Loading states
    SET_LOADING = "SET_LOADING",
    
    // Scan progress
    SET_SCAN_PROGRESS = "SET_SCAN_PROGRESS",
    CLEAR_SCAN_PROGRESS = "CLEAR_SCAN_PROGRESS",
    
    // Storage and system info
    SET_STORAGE_INFO = "SET_STORAGE_INFO",
    SET_SYSTEM_HEALTH = "SET_SYSTEM_HEALTH",
    SET_FEATURE_PROGRESS = "SET_FEATURE_PROGRESS",
}

export default {};
