export enum ActionTypes {
  
    
    // Scanner results
    SET_WHATSAPP_RESULTS = "SET_WHATSAPP_RESULTS",
    SET_LARGE_FILE_RESULTS = "SET_LARGE_FILE_RESULTS",
    SET_OLD_FILE_RESULTS = "SET_OLD_FILE_RESULTS",
    SET_DUPLICATE_RESULTS = "SET_DUPLICATE_RESULTS",
    SET_VIDEOS_RESULTS = "SET_VIDEOS_RESULTS",
    SET_IMAGES_RESULTS = "SET_IMAGES_RESULTS",
    SET_AUDIOS_RESULTS = "SET_AUDIOS_RESULTS",
    SET_DOCUMENTS_RESULTS = "SET_DOCUMENTS_RESULTS",
    
    // Clear results
    CLEAR_WHATSAPP_RESULTS = "CLEAR_WHATSAPP_RESULTS",
    CLEAR_LARGE_FILE_RESULTS = "CLEAR_LARGE_FILE_RESULTS",
    CLEAR_OLD_FILE_RESULTS = "CLEAR_OLD_FILE_RESULTS",
    CLEAR_DUPLICATE_RESULTS = "CLEAR_DUPLICATE_RESULTS",
    CLEAR_VIDEOS_RESULTS = "CLEAR_VIDEOS_RESULTS",
    CLEAR_IMAGES_RESULTS = "CLEAR_IMAGES_RESULTS",
    CLEAR_AUDIOS_RESULTS = "CLEAR_AUDIOS_RESULTS",
    CLEAR_DOCUMENTS_RESULTS = "CLEAR_DOCUMENTS_RESULTS",
    
    // Selected items
    SET_SELECTED_ITEMS = "SET_SELECTED_ITEMS",
    TOGGLE_ITEM_SELECTION = "TOGGLE_ITEM_SELECTION",
    CLEAR_SELECTIONS = "CLEAR_SELECTIONS",
    
    // Loading states
    SET_LOADING = "SET_LOADING",
    
    // Scan progress
    SET_SCAN_PROGRESS = "SET_SCAN_PROGRESS",
    CLEAR_SCAN_PROGRESS = "CLEAR_SCAN_PROGRESS",
    
    // Storage and system info
    SET_STORAGE_INFO = "SET_STORAGE_INFO",
    SET_SYSTEM_HEALTH = "SET_SYSTEM_HEALTH",
    SET_FEATURE_PROGRESS = "SET_FEATURE_PROGRESS",
}

export default {};
